[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = ">=3.9,<4.0"
scipy = "*"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"